const HOST_EVENT = {
  QUERY_HOST: "QUERY_HOST",
  NEW_HOST: "NEW_HOST",
  DELETE_HOST: "DELETE_HOST",
};

const USER_EVENT = {
  LOGIN: "LOGIN",
  NEW_USER: "NEW_USER",
  DELETE_USER: "DELETE_USER",
};

module.exports = { HOST_EVENT, USER_EVENT };
